Support multiple python versions, update ascii art lib, tests

diff --git a/example/run_tests b/example/run_tests
--- a/example/run_tests
+++ b/example/run_tests
@@ -3,7 +3,8 @@
 set -e
 set -o pipefail
 cd /lambda
-if [ `lambda invoke | md5sum | cut -d ' ' -f 1` != '5cd3139eadee0a85b2bb9f2164f3b6f6' ]; then
-  echo 'ERROR: md5sum of output returned by lambda invoke did not match expected results'
+if [ `lambda invoke | md5sum | cut -d ' ' -f 1` != '53fb4322cc3fe840f02530054ef93603' ]; then
+  echo 'ERROR: md5sum of output returned by lambda invoke did not match expected results' 1&>2
+  exit 1
 fi
 
